package dds.demo.play;


/**
* dds/demo/play/Canvas2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

/**
* Updated by idl2j
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Canvas2D",
    keys = {}
)
public final class Canvas2D implements org.omg.CORBA.portable.IDLEntity
{
  public int width = (int)0;
  public int height = (int)0;

  public Canvas2D ()
  {
  } // ctor

  public Canvas2D (int _width, int _height)
  {
    width = _width;
    height = _height;
  } // ctor

} // class Canvas2D
