package dds.demo.play;


/**
* dds/demo/play/ColorRGB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

public final class ColorRGB implements org.omg.CORBA.portable.IDLEntity
{
  public short red = (short)0;
  public short green = (short)0;
  public short blue = (short)0;

  public ColorRGB ()
  {
  } // ctor

  public ColorRGB (short _red, short _green, short _blue)
  {
    red = _red;
    green = _green;
    blue = _blue;
  } // ctor

} // class ColorRGB
