package dds.demo.play;

/**
* dds/demo/play/ColorRGBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

public final class ColorRGBHolder implements org.omg.CORBA.portable.Streamable
{
  public dds.demo.play.ColorRGB value = null;

  public ColorRGBHolder ()
  {
  }

  public ColorRGBHolder (dds.demo.play.ColorRGB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dds.demo.play.ColorRGBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dds.demo.play.ColorRGBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dds.demo.play.ColorRGBHelper.type ();
  }

}
