package dds.demo.play;


/**
* dds/demo/play/Coord2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

public final class Coord2D implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Coord2D ()
  {
  } // ctor

  public Coord2D (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Coord2D
