package dds.demo.play;


/**
* dds/demo/play/Line2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

/**
* Updated by idl2j
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Line2D",
    keys = {"sid", "id"}
)
public final class Line2D implements org.omg.CORBA.portable.IDLEntity
{
  public int sid = (int)0;
  public int id = (int)0;
  public dds.demo.play.Coord2D begin = null;
  public dds.demo.play.Coord2D end = null;
  public dds.demo.play.ColorRGB color = null;

  public Line2D ()
  {
  } // ctor

  public Line2D (int _sid, int _id, dds.demo.play.Coord2D _begin, dds.demo.play.Coord2D _end, dds.demo.play.ColorRGB _color)
  {
    sid = _sid;
    id = _id;
    begin = _begin;
    end = _end;
    color = _color;
  } // ctor

} // class Line2D
