package dds.demo.play;


/**
* dds/demo/play/Shape2DHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

abstract public class Shape2DHelper
{
  private static String  _id = "IDL:dds/demo/play/Shape2D:1.0";

  public static void insert (org.omg.CORBA.Any a, dds.demo.play.Shape2D that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dds.demo.play.Shape2D extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [6];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "sid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "width",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "height",
            _tcOf_members0,
            null);
          _tcOf_members0 = dds.demo.play.Coord2DHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "coord",
            _tcOf_members0,
            null);
          _tcOf_members0 = dds.demo.play.ColorRGBHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "color",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (dds.demo.play.Shape2DHelper.id (), "Shape2D", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dds.demo.play.Shape2D read (org.omg.CORBA.portable.InputStream istream)
  {
    dds.demo.play.Shape2D value = new dds.demo.play.Shape2D ();
    value.sid = istream.read_long ();
    value.id = istream.read_long ();
    value.width = istream.read_long ();
    value.height = istream.read_long ();
    value.coord = dds.demo.play.Coord2DHelper.read (istream);
    value.color = dds.demo.play.ColorRGBHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dds.demo.play.Shape2D value)
  {
    ostream.write_long (value.sid);
    ostream.write_long (value.id);
    ostream.write_long (value.width);
    ostream.write_long (value.height);
    dds.demo.play.Coord2DHelper.write (ostream, value.coord);
    dds.demo.play.ColorRGBHelper.write (ostream, value.color);
  }

}
