package dds.demo.play;


/**
* dds/demo/play/Shape2D.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:22 PM CET
*/

/**
* Updated by idl2j
* from ../idl/ddsplay.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Shape2D",
    keys = {"sid", "id"}
)
public final class Shape2D implements org.omg.CORBA.portable.IDLEntity
{
  public int sid = (int)0;
  public int id = (int)0;
  public int width = (int)0;
  public int height = (int)0;
  public dds.demo.play.Coord2D coord = null;
  public dds.demo.play.ColorRGB color = null;

  public Shape2D ()
  {
  } // ctor

  public Shape2D (int _sid, int _id, int _width, int _height, dds.demo.play.Coord2D _coord, dds.demo.play.ColorRGB _color)
  {
    sid = _sid;
    id = _id;
    width = _width;
    height = _height;
    coord = _coord;
    color = _color;
  } // ctor

} // class Shape2D
