package dds.demo;


/**
* dds/demo/DeviceInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

/**
* Updated by idl2j
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "DeviceInfo",
    keys = {"deviceId"}
)
public final class DeviceInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String deviceId = null;
  public String description = null;

  public DeviceInfo ()
  {
  } // ctor

  public DeviceInfo (String _deviceId, String _description)
  {
    deviceId = _deviceId;
    description = _description;
  } // ctor

} // class DeviceInfo
