package dds.demo;


/**
* dds/demo/DeviceInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Thursday, 30 May 2013 18:45:58 o'clock CEST
*/

/**
* Updated by idl2j
* from ../idl/oximeter.idl
* jeudi 30 mai 2013 18 h 45 CEST
*/

import org.opensplice.mobile.dcps.keys.KeyList;

@KeyList(
    topicType = "DeviceInfo",
    keys = {"deviceId"}
)
public final class DeviceInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String deviceId = null;
  public String description = null;

  public DeviceInfo ()
  {
  } // ctor

  public DeviceInfo (String _deviceId, String _description)
  {
    deviceId = _deviceId;
    description = _description;
  } // ctor

} // class DeviceInfo
