package dds.demo;

/**
* dds/demo/DeviceInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Thursday, 30 May 2013 18:45:58 o'clock CEST
*/

public final class DeviceInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public dds.demo.DeviceInfo value = null;

  public DeviceInfoHolder ()
  {
  }

  public DeviceInfoHolder (dds.demo.DeviceInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dds.demo.DeviceInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dds.demo.DeviceInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dds.demo.DeviceInfoHelper.type ();
  }

}
