package dds.demo;

/**
* dds/demo/OximetryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

public final class OximetryHolder implements org.omg.CORBA.portable.Streamable
{
  public dds.demo.Oximetry value = null;

  public OximetryHolder ()
  {
  }

  public OximetryHolder (dds.demo.Oximetry initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dds.demo.OximetryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dds.demo.OximetryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dds.demo.OximetryHelper.type ();
  }

}
