package dds.demo;


/**
* dds/demo/Oximetry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

/**
* Updated by idl2j
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Oximetry",
    keys = {"deviceId"}
)
public final class Oximetry implements org.omg.CORBA.portable.IDLEntity
{
  public String deviceId = null;
  public int deviceType = (int)0;
  public int spO2 = (int)0;
  public int bpm = (int)0;
  public int rr = (int)0;
  public int pleth = (int)0;

  public Oximetry ()
  {
  } // ctor

  public Oximetry (String _deviceId, int _deviceType, int _spO2, int _bpm, int _rr, int _pleth)
  {
    deviceId = _deviceId;
    deviceType = _deviceType;
    spO2 = _spO2;
    bpm = _bpm;
    rr = _rr;
    pleth = _pleth;
  } // ctor

} // class Oximetry
