package dds.demo;


/**
* dds/demo/Pleth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Thursday, 30 May 2013 18:45:58 o'clock CEST
*/

/**
* Updated by idl2j
* from ../idl/oximeter.idl
* jeudi 30 mai 2013 18 h 45 CEST
*/

import org.opensplice.mobile.dcps.keys.KeyList;

@KeyList(
    topicType = "Pleth",
    keys = {"deviceId"}
)
public final class Pleth implements org.omg.CORBA.portable.IDLEntity
{
  public String deviceId = null;
  public float pleth = (float)0;

  public Pleth ()
  {
  } // ctor

  public Pleth (String _deviceId, float _pleth)
  {
    deviceId = _deviceId;
    pleth = _pleth;
  } // ctor

} // class Pleth
