package dds.demo;


/**
* dds/demo/Pleth.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

/**
* Updated by idl2j
* from ../idl/oximeter.idl
* Monday, January 12, 2015 5:31:23 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Pleth",
    keys = {"deviceId"}
)
public final class Pleth implements org.omg.CORBA.portable.IDLEntity
{
  public String deviceId = null;
  public float pleth = (float)0;

  public Pleth ()
  {
  } // ctor

  public Pleth (String _deviceId, float _pleth)
  {
    deviceId = _deviceId;
    pleth = _pleth;
  } // ctor

} // class Pleth
