package dds.demo.vehicle;


/**
* dds/demo/vehicle/CollisionEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

/**
* Updated by idl2j
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "CollisionEvent",
    keys = {}
)
public final class CollisionEvent implements org.omg.CORBA.portable.IDLEntity
{
  public int vid = (int)0;
  public int otherVid = (int)0;
  public float distance = (float)0;

  public CollisionEvent ()
  {
  } // ctor

  public CollisionEvent (int _vid, int _otherVid, float _distance)
  {
    vid = _vid;
    otherVid = _otherVid;
    distance = _distance;
  } // ctor

} // class CollisionEvent
