package dds.demo.vehicle;


/**
* dds/demo/vehicle/DistanceViolationEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

/**
* Updated by idl2j
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "DistanceViolationEvent",
    keys = {}
)
public final class DistanceViolationEvent implements org.omg.CORBA.portable.IDLEntity
{
  public int thisVid = (int)0;
  public int thatVid = (int)0;
  public float distance = (float)0;

  public DistanceViolationEvent ()
  {
  } // ctor

  public DistanceViolationEvent (int _thisVid, int _thatVid, float _distance)
  {
    thisVid = _thisVid;
    thatVid = _thatVid;
    distance = _distance;
  } // ctor

} // class DistanceViolationEvent
