package dds.demo.vehicle;

/**
* dds/demo/vehicle/VehicleRegionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

public final class VehicleRegionHolder implements org.omg.CORBA.portable.Streamable
{
  public dds.demo.vehicle.VehicleRegion value = null;

  public VehicleRegionHolder ()
  {
  }

  public VehicleRegionHolder (dds.demo.vehicle.VehicleRegion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dds.demo.vehicle.VehicleRegionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dds.demo.vehicle.VehicleRegionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dds.demo.vehicle.VehicleRegionHelper.type ();
  }

}
