package dds.demo.vehicle;


/**
* dds/demo/vehicle/VehicleRegion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

/**
* Updated by idl2j
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "VehicleRegion",
    keys = {"vid"}
)
public final class VehicleRegion implements org.omg.CORBA.portable.IDLEntity
{
  public int vid = (int)0;
  public int x = (int)0;
  public int y = (int)0;
  public int width = (int)0;
  public int height = (int)0;

  public VehicleRegion ()
  {
  } // ctor

  public VehicleRegion (int _vid, int _x, int _y, int _width, int _height)
  {
    vid = _vid;
    x = _x;
    y = _y;
    width = _width;
    height = _height;
  } // ctor

} // class VehicleRegion
