package dds.demo.vehicle;


/**
* dds/demo/vehicle/VehicleStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

/**
* Updated by idl2j
* from ../idl/vehicle.idl
* Monday, January 12, 2015 5:31:24 PM CET
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "VehicleStatus",
    keys = {"vid"}
)
public final class VehicleStatus implements org.omg.CORBA.portable.IDLEntity
{
  public int vid = (int)0;

  // Vehicle Position
  public int x = (int)0;
  public int y = (int)0;

  // Vehicle Size
  public int width = (int)0;
  public int height = (int)0;

  // Vehicle Motion Vector
  public int dx = (int)0;
  public int dy = (int)0;

  public VehicleStatus ()
  {
  } // ctor

  public VehicleStatus (int _vid, int _x, int _y, int _width, int _height, int _dx, int _dy)
  {
    vid = _vid;
    x = _x;
    y = _y;
    width = _width;
    height = _height;
    dx = _dx;
    dy = _dy;
  } // ctor

} // class VehicleStatus
